
services:

  sound-detector:
    extra_hosts:
      host.docker.internal: "host-gateway"

  playback-distributor:
    extra_hosts:
      host.docker.internal: "host-gateway"

  sound-player:
    extra_hosts:
      host.docker.internal: "host-gateway"

  # journal:
  #   extra_hosts:
  #     host.docker.internal: "host-gateway"