# An overrides overlay for the default configuration to be used by Visual Studio Code.
services:

  sound-detector:
    command: sleep infinity
    build:
      args:
        - SKIP_BUILD=1
        - USE_TFLITE=0
        - USE_RETRAINED_MODEL=1
        - REMOVE_DATASET_AFTER_TRAINING=1
    volumes:
      - ./.git:/app/.git
      - ./.devcontainer:/app/.devcontainer
      - ./.vscode:/app/.vscode
      - ./modules/sound-detector:/app/sound-detector

  playback-distributor:
    entrypoint: sleep infinity
    build:
      target: development
      args:
        - SKIP_BUILD=1
    volumes:
      - ./.git:/app/.git
      - ./.devcontainer:/app/.devcontainer
      - ./.vscode:/app/.vscode
      - ./modules/playback-distributor:/app/playback-distributor
      - ./lib/c/commons:/app/lib/c/commons
      # Binding an anonymous volume to the container's build folder effectively excludes
      # the build folder from the bind mount
      #
      #   https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
      #
      - /app/playback-distributor/build
      - /app/lib/c/commons/build

  sound-player:
    entrypoint: sleep infinity
    build:
      target: development
      args:
        - SKIP_BUILD=1
    volumes:
      - ./.git:/app/.git
      - ./.devcontainer:/app/.devcontainer
      - ./.vscode:/app/.vscode
      - ./modules/sound-player:/app/sound-player
      - ./lib/c/commons:/app/lib/c/commons
      # Binding an anonymous volume to the container's build folder effectively excludes
      # the build folder from the bind mount
      #
      #   https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
      #
      - /app/sound-player/build
      - /app/lib/c/commons/build
  
  journal:
    entrypoint: sleep infinity
    build:
      target: development
    volumes:
      - ./.git:/app/.git
      - ./.devcontainer:/app/.devcontainer
      - ./.vscode:/app/.vscode
      # Binding an anonymous volume to the container's node_modules effectively excludes
      # the node_modules folder from the bind mount `./modules/journal/app:/app/journal/app`.
      #
      #   https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
      #
      - ./modules/journal:/app/journal
      - /app/journal/node_modules