# NOTE: Docker Compose is used only for development. In production the system uses
# systemd to manage the services. Check the ansible files for more details.
#
# WARNING: Linux users will need to apply the `docker-compose.linux.yaml` file too:
#
#   docker-compose -f docker-compose.yaml -f docker-compose.linux.yaml up
#
version: "3"
services:

  # --- Sound Detector -----------------------------------------------------------------
  sound-detector:
    build:
      context: .
      dockerfile: ./sound-detector/Dockerfile
      args:
        DEBUG: 1
        INSTALL_DEV_DEPS: 1
        USE_TFLITE: 1
    # TODO: Run containers as non-root https://github.com/eulersson/taconez/issues/72
    user: root
    environment:
      - INFLUX_DB_HOST=influx-db-server
      - INFLUX_DB_TOKEN=no_token
      - PLAYBACK_DISTRIBUTOR_HOST=playback-distributor
      - PULSE_SERVER=host.docker.internal
      - SKIP_DETECTION_NOTIFICATION=False
      - SKIP_RECORDING=False
    volumes:
      - $HOME/.config/pulse/cookie:/root/.config/pulse/cookie
      - ./sound-detector:/app/sound-detector
      - ./prerolls:/app/prerolls
      - ./recordings:/app/recordings
    tty: true
    depends_on:
      - influx-db-server
      - playback-distributor

  # --- Playback Distributor -----------------------------------------------------------
  playback-distributor:
    build:
      context: .
      dockerfile: ./playback-distributor/Dockerfile
      args:
        DEBUG: 1
        DEPENDENCIES_COMPILE_FROM_SOURCE: 1
      target: development
    # TODO: Run containers as non-root https://github.com/eulersson/taconez/issues/72
    user: root
    volumes:
      - ./playback-distributor/Dockerfile:/app/playback-distributor/Dockerfile
      - ./playback-distributor/src:/app/playback-distributor/src
      - ./playback-distributor/CMakeLists.txt:/app/playback-distributor/CMakeLists.txt
      - ./playback-distributor/tests:/app/playback-distributor/tests
      - ./lib/c/commons/CMakeLists.txt:/app/lib/c/commons/CMakeLists.txt
      - ./lib/c/commons/include:/app/lib/c/commons/include
      - ./lib/c/commons/src:/app/lib/c/commons/src
      - ./prerolls:/app/prerolls:ro
      - ./recordings:/app/recordings:ro
    tty: true

  # --- Sound Player -------------------------------------------------------------------
  sound-player:
    build:
      context: .
      dockerfile: ./sound-player/Dockerfile
      args:
        DEBUG: 1
        DEPENDENCIES_COMPILE_FROM_SOURCE: 1
      target: development
    image: taconez/sound-player:dev
    # TODO: Run containers as non-root https://github.com/eulersson/taconez/issues/72
    user: root
    environment:
      - PULSE_SERVER=host.docker.internal
      - PLAYBACK_DISTRIBUTOR_HOST=playback-distributor
    volumes:
      - $HOME/.config/pulse/cookie:/root/.config/pulse/cookie
      - ./sound-player/Dockerfile:/app/sound-player/Dockerfile
      - ./sound-player/src:/app/sound-player/src
      - ./sound-player/CMakeLists.txt:/app/sound-player/CMakeLists.txt
      - ./sound-player/tests:/app/sound-player/tests
      - ./lib/c/commons/CMakeLists.txt:/app/lib/c/commons/CMakeLists.txt
      - ./lib/c/commons/include:/app/lib/c/commons/include
      - ./lib/c/commons/src:/app/lib/c/commons/src
      - ./prerolls:/app/prerolls:ro
      - ./recordings:/app/recordings:ro
    tty: true
    depends_on:
      - playback-distributor

  # --- InfluxDB Server ----------------------------------------------------------------
  influx-db-server:
    image: influxdb:2.7.4-alpine
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: taconez
      DOCKER_INFLUXDB_INIT_PASSWORD: ufftQDZNDESRALXi5NbS
      DOCKER_INFLUXDB_INIT_ORG: taconez
      DOCKER_INFLUXDB_INIT_BUCKET: taconez
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: no_token
