# An overrides overlay for the default configuration to be used by Visual Studio Code.
services:

  sound-detector:
    entrypoint: sleep infinity
    build:
      args:
        - SKIP_BUILD=1
    volumes:
      - ./.git:/app/.git
      - ./.devcontainer:/app/.devcontainer
      - ./.vscode:/app/.vscode
      - ./sound-detector:/app/sound-detector

  playback-distributor:
    entrypoint: sleep infinity
    build:
      target: development
      args:
        - SKIP_BUILD=1
    volumes:
      - ./.git:/app/.git
      - ./.devcontainer:/app/.devcontainer
      - ./.vscode:/app/.vscode
      # Binding an anonymous volume to the container's node_modules effectively excludes
      # the node_modules folder from the bind mount `./journal/app:/app/journal/app`.
      #
      #   https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
      #
      - ./playback-distributor:/app/playback-distributor
      - ./lib/c/commons:/app/lib/c/commons
      - /app/playback-distributor/build
      - /app/lib/c/commons/build

  sound-player:
    entrypoint: sleep infinity
    build:
      target: development
      args:
        - SKIP_BUILD=1
    volumes:
      - ./.git:/app/.git
      - ./.devcontainer:/app/.devcontainer
      - ./.vscode:/app/.vscode
  
  journal:
    entrypoint: sleep infinity
    build:
      target: development
    volumes:
      - ./.git:/app/.git
      - ./.devcontainer:/app/.devcontainer
      - ./.vscode:/app/.vscode
      # Binding an anonymous volume to the container's node_modules effectively excludes
      # the node_modules folder from the bind mount `./journal/app:/app/journal/app`.
      #
      #   https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
      #
      - ./sound-player:/app/sound-player
      - /app/sound-player/build
      - /app/lib/c/commons/build