# An overrides overlay for the default configuration to be used by Visual Studio Code.
services:

  sound-detector:
    entrypoint: sleep infinity
    build:
      args:
        - SKIP_BUILD=1
    volumes:
      - ./.git:/app/.git
      - ./.devcontainer:/app/.devcontainer
      - ./.vscode:/app/.vscode

  playback-distributor:
    entrypoint: sleep infinity
    build:
      args:
        - SKIP_BUILD=1
    volumes:
      - ./.git:/app/.git
      - ./.devcontainer:/app/.devcontainer
      - ./.vscode:/app/.vscode

  sound-player:
    entrypoint: sleep infinity
    build:
      args:
        - SKIP_BUILD=1
    volumes:
      - ./.git:/app/.git
      - ./.devcontainer:/app/.devcontainer
      - ./.vscode:/app/.vscode
  
  journal:
    entrypoint: sleep infinity
    build:
      target: development
    volumes:
      - ./.git:/app/.git
      - ./.devcontainer:/app/.devcontainer
      - ./.vscode:/app/.vscode