# NOTE: Docker Compose is used only for development. In production the system uses
# systemd to manage the services. Check the ansible files for more details.
#
# WARNING: Linux users will need to apply the `docker-compose.linux.yaml` file too:
#
#   docker-compose -f docker-compose.yaml -f docker-compose.linux.yaml up
#
version: "3"
services:

  # --- Sound Detector -----------------------------------------------------------------
  sound-detector:
    build:
      context: .
      dockerfile: ./sound-detector/Dockerfile
      args:
        DEBUG: 1
        INSTALL_DEV_DEPS: 1
        USE_TFLITE: 1
    # TODO: Run containers as non-root https://github.com/eulersson/taconez/issues/72
    user: root
    environment:
      - INFLUX_DB_HOST=influx-db-server
      - INFLUX_DB_TOKEN=no_token
      - PLAYBACK_DISTRIBUTOR_HOST=playback-distributor
      - PULSE_SERVER=host.docker.internal
      - SKIP_DETECTION_NOTIFICATION=False
      - SKIP_RECORDING=False
    volumes:
      - ./prerolls:/app/prerolls
      - ./recordings:/app/recordings
      - $HOME/.config/pulse/cookie:/root/.config/pulse/cookie
      - ./sound-detector:/app/sound-detector
    depends_on:
      - influx-db-server
      - playback-distributor

  # --- Playback Distributor -----------------------------------------------------------
  playback-distributor:
    build:
      context: .
      dockerfile: ./playback-distributor/Dockerfile
      args:
        DEBUG: 1
        DEPENDENCIES_COMPILE_FROM_SOURCE: 1
      target: production
    # TODO: Run containers as non-root https://github.com/eulersson/taconez/issues/72
    user: root
    volumes:
      - ./prerolls:/app/prerolls:ro
      - ./recordings:/app/recordings:ro
      - ./playback-distributor:/app/playback-distributor
      - ./lib/c/commons:/app/lib/c/commons
      # Binding an anonymous volume to the container's node_modules effectively excludes
      # the node_modules folder from the bind mount `./journal/app:/app/journal/app`.
      #
      #   https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
      #
      - /app/playback-distributor/build
      - /app/lib/c/commons/build

  # --- Sound Player -------------------------------------------------------------------
  sound-player:
    build:
      context: .
      dockerfile: ./sound-player/Dockerfile
      args:
        DEBUG: 1
        DEPENDENCIES_COMPILE_FROM_SOURCE: 1
      target: development
    image: taconez/sound-player:dev
    # TODO: Run containers as non-root https://github.com/eulersson/taconez/issues/72
    user: root
    environment:
      - PULSE_SERVER=host.docker.internal
      - PLAYBACK_DISTRIBUTOR_HOST=playback-distributor
    volumes:
      - ./prerolls:/app/prerolls:ro
      - ./recordings:/app/recordings:ro
      - $HOME/.config/pulse/cookie:/root/.config/pulse/cookie
      - ./sound-player:/app/sound-player
      - ./lib/c/commons:/app/lib/c/commons
      # Binding an anonymous volume to the container's node_modules effectively excludes
      # the node_modules folder from the bind mount `./journal/app:/app/journal/app`.
      #
      #   https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
      #
      - /app/sound-player/build
      - /app/lib/c/commons/build
    depends_on:
      - playback-distributor
  
  # --- Journal ------------------------------------------------------------------------
  journal:
    build:
      context: .
      dockerfile: ./journal/Dockerfile
      target: development
    image: taconez/journal:dev
    volumes:
      - ./journal:/app/journal
      # Binding an anonymous volume to the container's node_modules effectively excludes
      # the node_modules folder from the bind mount `./journal/app:/app/journal/app`.
      #
      #   https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
      #
      - /app/journal/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - influx-db-server

  # --- InfluxDB Server ----------------------------------------------------------------
  influx-db-server:
    image: influxdb:2.7.4-alpine
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: taconez
      DOCKER_INFLUXDB_INIT_PASSWORD: ufftQDZNDESRALXi5NbS
      DOCKER_INFLUXDB_INIT_ORG: taconez
      DOCKER_INFLUXDB_INIT_BUCKET: taconez
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: no_token
    ports:
      - "8086:8086"
