---
# Install libraries that are common across modules.

- name: Create folder for the common library files
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: taconez
    group: taconez
    mode: 0755
  loop:
    - "{{ project_root_remote }}/lib"

- name: Synchronize common library files
  synchronize:
    src: "{{ project_root_local }}/lib"
    dest: "{{ project_root_remote }}/"
    delete: true
    rsync_opts:
      - "--exclude-from={{ project_root_local }}/modules/playback-distributor/.rsync-exclude"

- name: Synchronize other files that are shared across modules
  synchronize:
    src: "{{ project_root_local }}/{{ item }}"
    dest: "{{ project_root_remote }}/"
    delete: true
  loop:
    - .asoundrc
    - .dockerignore

# Create /apps/taconez/prerolls and dataset if they don't exist.
- name: Create folder for the prerolls
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: taconez
    group: taconez
    mode: 0755
  loop:
    - "{{ project_root_remote }}/prerolls"
    - "{{ project_root_remote }}/dataset"
  
# Copy the prerolls to the remote server.
- name: Copy prerolls to the remote server
  synchronize:
    src: "{{ project_root_local }}/prerolls"
    dest: "{{ project_root_remote }}/"
    delete: true