---
# Installs dependencies that are common among master and slave Raspberry Pi nodes.

- name: Install audio dependencies
  import_tasks: audio.yml
  tags: [audio]

- name: Install Docker
  import_tasks: docker.yml
  tags: [docker]

- name: Install common libraries
  import_tasks: common-libs.yml
  tags: [common-libs]

- name: Build and run Sound Detector module
  import_tasks: sound-detector.yml
  tags: [sound-detector]

- name: Build and run Sound Player module
  import_tasks: sound-player.yml
  tags: [sound-player]
