---
# Synchronizes the project files to the remote system.

- name: Create app folder for project files
  become: true
  file:
    path: /app/anesowa
    state: directory
    owner: anesowa
    group: anesowa
    mode: "0755"

- name: Synchronize project files
  synchronize:
    src: "{{ project_root }}/"
    dest: /app/anesowa
    rsync_opts:
      - "--exclude-from={{ project_root }}/rsync_exclude.txt"
  tags:
    - sync-project
