---
# Builds and runs the Sound Detector module.

- name: Create folder for the Sound Detector module and its service scripts
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: taconez
    group: taconez
    mode: 0755
  loop:
    - "{{ project_root_remote }}/modules/sound-detector"
    - "{{ services_root_remote }}/sound-detector"

- name: Create directory where recordings will go in case it doesn't exist
  become: true
  file:
    path: "/mnt/nfs/taconez"
    state: directory
    owner: taconez
    group: taconez
    mode: 0755

- name: Synchronize Sound Detector project files
  synchronize:
    src: "{{ project_root_local }}/modules/sound-detector/"
    dest: "{{ project_root_remote }}/modules/sound-detector"
    delete: true
    rsync_opts:
      - "--exclude-from={{ project_root_local }}/modules/sound-detector/.rsync-exclude"

- name: Install Sound Detector service scripts (ExecStart, ExecStop)
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
  loop:
    - src: "{{ project_root_local }}/modules/sound-detector/service/exec-start.sh"
      dest: "{{ services_root_remote }}/sound-detector/exec-start.sh"
    - src: "{{ project_root_local }}/modules/sound-detector/service/exec-stop.sh"
      dest: "{{ services_root_remote }}/sound-detector/exec-stop.sh"
  tags: [service, service-sound-detector]

- name: Install Sound Detector service
  become: true
  template:
    src: "{{ project_root_local }}/modules/sound-detector/service/sound-detector.service.j2"
    dest: /etc/systemd/system/taconez-sound-detector.service
  tags: [service, service-sound-detector]

- name: Ensure Sound Detector service is stopped
  become: true
  systemd:
    name: taconez-sound-detector.service
    state: stopped

- name: Ensure no Sound Detector containers exist
  become: true
  docker_container:
    name: taconez-sound-detector
    state: absent

- name: Build Sound Detector image
  # sudo docker build -f /app/taconez/modules/sound-detector/Dockerfile --build-arg DEBUG=0 --build-arg INSTALL_DEV_DEPS=0 --build-arg USE_TFLITE=1 --build-arg STEALTH_MODE=0 .
  become: true
  docker_image:
    force_source: true
    build:
      dockerfile: "{{ project_root_remote }}/modules/sound-detector/Dockerfile"
      path: "{{ project_root_remote }}"
      args:
        DEBUG: "{{ debug }}"
        INSTALL_DEV_DEPS: 0
        USE_TFLITE: 1
        STEALTH_MODE: "{{ stealth_mode }}"
    name: taconez/sound-detector
    tag: "{{ project_version }}"
    source: build
  when: force_docker_image_rebuild

- name: Clean dangling images
  become: true
  docker_prune:
    images: true
    images_filters: dangling=true

- name: Restart Sound Detector service
  become: true
  systemd_service:
    daemon_reload: true
    enabled: true
    state: restarted
    name: taconez-sound-detector.service
  tags: [service, service-sound-detector]
