---
# Variables listed here are applicable to all host groups

ansible_user: taconez
ansible_ssh_private_key_file: ~/.ssh/raspberry_local
project_version: 1.0.0
project_root_local: "{{ playbook_dir | dirname }}"
project_root_remote: /app/taconez
services_root_remote: /app/taconez-services
python_virtualenv: /app/venv
force_docker_image_rebuild: true
debug: false
logging_level: INFO

# The "monitor" mode is useful for gathering sound data and see what categories are
# detected. The "detection" mode is useful when you want to react against a specific
# category of sound.
stealth_mode: true