---
# Variables listed here are applicable to all host groups

ansible_user: taconez
ansible_ssh_private_key_file: ~/.ssh/raspberry_local
project_version: 1.0.0
project_root_local: "{{ playbook_dir | dirname }}"
project_root_remote: /app/taconez
services_root_remote: /app/taconez-services
python_virtualenv: /app/venv
force_docker_image_rebuild: true