---
# Tasks particular to the Raspberry Pi master node.

- name: Install and configure InfluxDB
  import_tasks: influx-db.yml
  tags:
    - influx-db

- name: Install NFS and configure a share
  import_tasks: nfs.yml
  tags:
    - nfs

- name: Building Playback Distributor module
  import_tasks: playback-distributor.yml
  tags: [playback-distributor]

- name: Prepare Journal Web App
  import_tasks: journal.yml
  tags:
    - journal
