---
# Configures NFS to be used as a client.

- name: Create app folder to turn into an NFS share
  become: true
  file:
    path: "/mnt/nfs/taconez"
    state: directory
    owner: taconez
    group: taconez
    mode: 0755

- name: Mount the NFS share from the master
  become: true
  command: mount --types nfs --verbose rpi-master.local:/mnt/nfs/taconez /mnt/nfs/taconez